### ISSUE TITLE
update CSS cheatsheet

### ISSUE THREAD

**Issue by loretogutierrezjr** [aryankashyap7/CheatSheets-for-Developers#80]
Hi, Aryan,
I added some info. in CSS.
Please check if possible to merge? Thanks.

**Comment by aryankashyap7** [comment]
@loretogutierrezjr Elaborate more on the changes you wanna add over there.

**Comment by loretogutierrezjr** [comment]
> @loretogutierrezjr Elaborate more on the changes you wanna add over there.
Hi Aryan,
I'm not sure how to display here my pull request but here is the added info.

## CSS

### BASICS
`Syntax` - basic code sctructure of CSS
```css
   selector { 
    property: value; 
    property2: value2; }
```

`Clearfix` - to clear its child elements automatically without any additional markup.
```css
    .clearfix:after {
        clear: both;
        content: " ";
        display: block;
        font-size: 0;
        height: 0;
        visibility: hidden; }
    .clearfix { display: inline-block; }
    * html .clearfix { height: 1%; }
    .clearfix { display: block; }
```



### SELECTORS & Descriptions
| Selectors             | Descriptions                          |
| --------------------- | --------------------------------------|
| *                     | all elements                          |
| div                   | all div tags                          |
| div,p                 | all divs and paragraphs               |
| div p                 | paragraphs inside divs                |
| div > p               | all p tags, one level deep in div     |
| div + p               | p tags immediately after div          |
| div ~ p               | p tags preceded by div                |
| .classname            | all elements with class               |
| #idname               | element with ID                       |
| div.classname         | divs with certain classname           |
| div#idname            | div with certain ID                   |
| #idname*              | all elements inside #idname           |
